### ISSUE TITLE
Searching for program: No such file or directory, zsh

### ISSUE THREAD

**Issue by ndegruchy** [xenodium/dwim-shell-command#1]
It appears as though `dwim-shell-command` requires zsh? Is that the case? Are we able to customize it to use bash, or another shell?

Thanks!

**Comment by xenodium** [comment]
Added `dwim-shell-command-shell-util` and `dwim-shell-command-shell-args` variables to make it configurable. Can you try setting `dwim-shell-command-shell-util` to "bash"? Please update and try again.

**Comment by xenodium** [comment]
ps. `dwim-shell-command-shell-util` and `dwim-shell-command-shell-args` default values should now work for most folks (shell-file-name and shell-command-switch are now also considered).

**Comment by ndegruchy** [comment]
Yep! That works!
