### ISSUE TITLE
dwim-shell-comands-open-externally stopped working on linux

### ISSUE THREAD

**Issue by saucoide** [xenodium/dwim-shell-command#12]
Hi, not sure at what point it started to happen but `dwim-shell-commands-open-externally` doesnt seem to work anymore on linux (on macos it does work) the function runs and seems to complete successfully but nothing really happens

running xdg-open from the terminal does work, and running it from dired as `!xdg-open` also works so i think it's something with dwim-shell-command, but i couldn't pinpoint exactly what it is

happy to help if there is anything i can do
thanks!

**Comment by xenodium** [comment]
Hi @saucoide. Don't have a linux machine handy, but could you try the following version of the function with some logging to see if we spot anything wrong?

```emacs-lisp
(defun dwim-shell-commands-open-externally ()
  "Open file(s) externally."
  (interactive)
  (dwim-shell-command-on-marked-files
   "Open externally"
   (if (eq system-type 'darwin)
       "open '<<f>>'"
     "xdg-open '<<f>>'")
   :shell-args '("-x" "-c")
   :utils (if (eq system-type 'darwin)
              "open"
            "xdg-open")))
```

**Comment by xenodium** [comment]
ps. Look out for a `✅ *Open externally* done` buffer or similar (without success bits).

**Comment by saucoide** [comment]
i'm on the fish shell so i modified the function to use fish's debugging:

```elisp
(defun dwim-shell-commands-open-externally ()
  "Open file(s) externally."
  (interactive)
  (dwim-shell-command-on-marked-files
   "Open externally"
   (if (eq system-type 'darwin)
       "open '<<f>>'"
     "xdg-open '<<f>>'")
   :shell-args '("-d" "*" "-c")
   :utils (if (eq system-type 'darwin)
              "open"
            "xdg-open")))
```

the relevant part:

```exec-fork: Fork #11, pid 8890: spawn external command '/usr/bin/xdg-open' from '<no file>'
exec-job-exec: Executed job 1 from command 'xdg-open '/home/saucoide/downloads/use-gnu-emacs.html''
proc-job-run: Run job 1 (xdg-open '/home/saucoide/downloads/use-gnu-emacs.html'), UNCOMPLETED, NON-INTERACTIVE
proc-reap-external: Reaped external process 'xdg-open' (pid 8890, status 0)
```

i dont see anything wrong here either so i dont know :/ maybe it's not this package

**Comment by mgsb** [comment]
I looked into this since I was having this problem, too, on Linux. I found various threads about problems with xdg-open and async processes in emacs, e.g., 

I modified dwim-shell-command.el:463 to set process-connection-type to nil and it works now (untested on other OSs). This is with emacs 29.1 and ubuntu 22.04.

    (let ((process-connection-type nil))
        (setq proc (apply #'start-process (seq-concatenate 'list
                                                           (list (buffer-name proc-buffer) proc-buffer)
                                                           shell-util
                                                           shell-args
                                                           (if shell-pipe
                                                               (list (format "echo '%s' | %s" script shell-pipe))
                                                             (list script))))))

**Comment by mgsb** [comment]
Example post about the issue: https://askubuntu.com/questions/646631/emacs-doesnot-work-with-xdg-open

**Comment by saucoide** [comment]
thanks! that setting breaks other things though, i ended up using `setsid` on the bit that calls xdg-open

`"setsid -w xdg-open '<<f>>'"`

but yes the problem was definetly that xdg-open returns sucessfully and any child processes gets killed with it

**Comment by xenodium** [comment]
Thank you both!

If this issue manifests with some shells and the command is pretty much shell-agnostic (like the open case), can't we explicitly set the shell for this command? `:shell-util "zsh"`.

```emacs-lisp
(defun dwim-shell-commands-open-externally ()
  "Open file(s) externally."
  (interactive)
  (dwim-shell-command-on-marked-files
   "Open externally"
   (if (eq system-type 'darwin)
       (if (derived-mode-p 'prog-mode)
           (format "xed --line %d '<<f>>'"
                   (line-number-at-pos (point)))
         "open '<<f>>'")
     "xdg-open '<<f>>'")
   :shell-util "zsh"
   :shell-args '("-x" "-c")
   :silent-success t
   :utils (if (eq system-type 'darwin)
              "open"
            "xdg-open")))
```

Does this work for ya?

**Comment by xenodium** [comment]
> "setsid -w xdg-open '<<f>>'"

ps. If this works for both of you, happy to take this change. Sorry, not on Linux these days, so can't verify it.

**Comment by mgsb** [comment]
I think you mean:

(defun dwim-shell-commands-open-externally ()
  "Open file(s) externally."
  (interactive)
  (dwim-shell-command-on-marked-files
   "Open externally"
   (if (eq system-type 'darwin)
       (if (derived-mode-p 'prog-mode)
           (format "xed --line %d '<<f>>'"
                   (line-number-at-pos (point)))
         "open '<<f>>'")
     "setsid -w xdg-open '<<f>>'")
   :shell-args '("-x" "-c")
   :silent-success t
   :utils (if (eq system-type 'darwin)
              "open"
            "xdg-open")))

as @saucoide suggested. This works for me.

**Comment by xenodium** [comment]
Thank you. Pushed the change.

**Comment by saucoide** [comment]
@xenodium you were right, the solution you first proposed:

```elisp
(defun dwim-shell-commands-open-externally ()
  "Open file(s) externally."
  (interactive)
  (dwim-shell-command-on-marked-files
   "Open externally"
   (if (eq system-type 'darwin)
       (if (derived-mode-p 'prog-mode)
           (format "xed --line %d '<<f>>'"
                   (line-number-at-pos (point)))
         "open '<<f>>'")
     "xdg-open '<<f>>'")
   :shell-util "zsh"
   :shell-args '("-x" "-c")
   :silent-success t
   :utils (if (eq system-type 'darwin)
              "open"
            "xdg-open")))
```

is a better option, i upgraded the module today & removed my patch and it broke :) i was on an older version that
did not have `:shell-args '("-x" "-c")` , fish does not take those args, so now it errors out, so changing which shell it uses seems better, that way we don't need to worry about non compatible shell arguments

**Comment by xenodium** [comment]
Nice to hear. Happy holidays!
