### ISSUE TITLE
Surprising behaviour when `default-directory` is bound

### ISSUE THREAD

**Issue by pkryger** [xenodium/dwim-shell-command#14]
I have some commands, that I want to run in a project root, and I'm primarily interested in the std out/err of them. When I bind `default-directory` to project root what happens is:
- a `dired` buffer is popped (with a directory of containing the file that was visited when the command has been called).
- buffer of the command output does not exist.

An example command, that exhibits this behaviour is:
``` emacs-lisp
(defun dwim-shell-command-hello-world-in-project-root ()
  (interactive)
  (let ((default-directory (project-root (project-current))))
    (dwim-shell-command-execute-script "hello world"
                                       "echo \"[$(pwd)] Hello World!\"")))
```

As a workaround I'm using injection of the project root into the script, like in the following example:
``` emacs-lisp
(defun dwim-shell-command-hello-world-in-project-root ()
  (interactive)
  (let ((project-root (project-root (project-current))))
    (dwim-shell-command-execute-script
     "hello world"
     (format "cd '%s'
              echo \"[$(pwd)] Hello World!\""
             project-root))))
```
However, I think I prefer the former solution better. It's not only shorter, but I think more robust as well, i.e., it's easy to forget about quoting the argument to `cd` (would that prevent all corner cases?).

**Comment by xenodium** [comment]
Sorry for the delay.

Have you tried something like the following?

```emacs-lisp
(defun dwim-shell-command-hello-world-in-project-root ()
  (interactive)
  (let ((default-directory (project-root (project-current))))
    (dwim-shell-command-on-marked-files "hello world"
                                        "echo \"[$(pwd)] Hello World!\"")))
```

> I want to run in a project root, and I'm primarily interested in the std out/err of them. 

The above should give you this. It should automatically drop you to the output buffer when command finishes.

**Comment by pkryger** [comment]
> Have you tried something like the following?
> 
> ```emacs-lisp
> (defun dwim-shell-command-hello-world-in-project-root ()
>   (interactive)
>   (let ((default-directory (project-root (project-current))))
>     (dwim-shell-command-on-marked-files "hello world"
>                                         "echo \"[$(pwd)] Hello World!\"")))
> ```
> [...]
> The above should give you this. It should automatically drop you to the output buffer when command finishes.

I did tried that. The result is a `dired` buffer opened in a directory that contains the visited file at the moment of invocation.

**Comment by xenodium** [comment]
Did you by chance try a different command different to the "hello world" one? If so, could you share that too, please? I'm asking as there's logic in `dwim-shell-command` to jump to a dired buffer if there were files generated for the command. This is typically useful for quickly accessing generated files, for example converting png to jpg.

**Comment by xenodium** [comment]
Ah, sorry... Spoke too soon. It only works without overriding  project root.

```emacs-lisp
(defun dwim-shell-command-hello-world-in-project-root ()
  (interactive)
  (dwim-shell-command-on-marked-files
     "hello world"
     "echo \"[$(pwd)] Hello World!\""))
```

Lemme investigate a little...

**Comment by xenodium** [comment]
Pushed a fix in https://github.com/xenodium/dwim-shell-command/commit/8b90a964f09e69b1c55258e91710b0488e0bf135. Lemme know if that doesn't work.

**Comment by pkryger** [comment]
It does work 🥳. Thank you for the fix!

**Comment by xenodium** [comment]
Yay. Glad to hear.
