### ISSUE TITLE
How to use it with scp

### ISSUE THREAD

**Issue by tareefdev** [xenodium/dwim-shell-command#2]
I'm trying to write a function using this tool to copy files over an ssh connection. Here is what I'm trying to achieve:

- Using Dired tramp to navigate to a remote machine.
- Trying to call the following function on a remote file
```lsip
(defun my/dwim-shell-command-copy-from-remote-dir ()
    "Convert all marked videos to optimized gif(s)."
    (interactive)
    (dwim-shell-command-on-marked-files
     "Copy to local"
     "scp <<f>> ~/"))
```
- The library gives an error that says `'/ssh:tareef@example.com:/home/tareef/file.org': No such file or directory`

The scp tool expects a path that starts with `username@ip`, but the `<<f>>`  path starts with `/ssh:`, which makes the command fails.

What is the proper way to handle this situation?

**Comment by xenodium** [comment]
Ah, I hadn't thought about tramp, but... I think this kinda works?

    (dwim-shell-command-on-marked-files
     "Copy to local"
     "scp '<<f>>' ~/"
     :utils "scp"
     :post-process-template (lambda (script file)
                              (string-replace "/ssh:" "" script)))

**Comment by tareefdev** [comment]
Modifying the string does the trick. Thanks!

**Comment by xenodium** [comment]
Good to hear!

**Comment by xenodium** [comment]
ps. @tareefdev if you'd like to make the replacement a little safer, you can do:

    (dwim-shell-command-on-marked-files
     "Copy remote to local Downloads"
     "scp '<<f>>' ~/Downloads/"
     :utils "scp"
     :post-process-template
     (lambda (script file)
       ;; Tramp file path start with "/ssh:". Drop it.
       (string-replace file
                       (string-remove-prefix "/ssh:" file)
                       script)))

**Comment by tareefdev** [comment]
Thank you!
