### ISSUE TITLE
Autoloading dwim-shell-commands commands

### ISSUE THREAD

**Issue by krisbalintona** [xenodium/dwim-shell-command#21]
I think it'd be good to autoload the commands in `dwim-shell-commands`. I lazy load the package with use-package and currently have to manually load the package to have those commands available with M-x.

**Comment by xenodium** [comment]
No objection here. Mind sending a pull request?

**Comment by xenodium** [comment]
Ok, added them all. Can you tey them out?

**Comment by krisbalintona** [comment]
> Ok, added them all. Can you tey them out?

Looks great! Thank you!

**Comment by xenodium** [comment]
Nice to hear. Thank you! If you find this package useful, consider [sponsoring](https://github.com/sponsors/xenodium) to make the work sustainable.
