### ISSUE TITLE
optionally quote <<*>> expansion for pathological filenames

### ISSUE THREAD

**Issue by gvoysey** [xenodium/dwim-shell-command#3]
when using `dwim-shell-command` with dired to mark and operate on multiple files with horrible names like `foo (1).zip`  or `november '21 datasheet.xls`, no quoting is applied in the <<*>> noweb form.  Could this become an option?  Right now, you'll get errors like `zsh:1: unmatched '`  instead.

**Comment by xenodium** [comment]
Is it also failing if you quote around it?

For example: `ls '<<*>>'`

<img width="554" alt="Screenshot 2022-10-07 at 12 39 16" src="https://user-images.githubusercontent.com/8107219/194545481-04bdf66a-7409-496d-878f-4b94f45c00bb.png">

**Comment by gvoysey** [comment]
`command '<<*>>'` still fails if one of the files has a single quote in the filename.  
`command "<<*>>"` fails because `The file \`/the/full/path/filea /the/full/path/fileb\`` doesn't exist -- the double quotes are wrapping the list, not each file item. 

I _think_ what's needed is a way to doublequote each element in the <<*>> expansion as a general solution.

**Comment by xenodium** [comment]
@gvoysey please retry with the latest (0.21). Same usage. Could be `ls '<<*>>'` or `ls "<<*>>"`. Please reopen if you still run into issues.

**Comment by gvoysey** [comment]
works  like a charm.  cheers!

**Comment by xenodium** [comment]
Good to hear. Nice to see the usages too.

**Comment by xenodium** [comment]
@gvoysey forgot to mention `:silent-success t` is the explicit equivalent of `leading whitespace suppresses output buffer display`.

    (defun dwim-shell-command-feh-marked-files ()
      "View all marked files with feh."
      (interactive)
      (dwim-shell-command-on-marked-files
       "View with feh"
       "feh --auto-zoom --scale-down '<<*>>'"
       :silent-success t
       :utils "feh"))

The leading space exists, so it can be easily used via "M-x dwim-shell-command".

**Comment by gvoysey** [comment]
ah!  that's much nicer :)
