### ISSUE TITLE
Symbol's function definition is void: string-replace

### ISSUE THREAD

**Issue by strickinato** [xenodium/dwim-shell-command#4]
👋 --

I'm a doom-emacs user (as such, as you can imagine, I don't have very good understanding of how packages get loaded, etc.) 

I wanted to try out this package, but I ran into some trouble. I don't think it's necessarily an issue with `dwim-shell-command` - (I could be doing something wrong), but also, I figured you could help.

Basically, whenever I run a command, I get the error: `Symbol's function definition is void: string-replace`

* Indeed, when I run `describe-function`, `string-replace` is not defined.
* I don't see it defined in your package.
* I tried re-evaluating all the `(require ___)` statements that your package depends on, thinking maybe there was something about how I included your package that the dependencies weren't run (or that I didn't have them on my system). But all the require statements happily evaluated, and `string-replace` is still not defined.
* I also looked through your dotfiles to see if it was maybe something you defined on your instance, and I didn't seen anything there.

So, what am I missing? Where does `string-replace` come from?

Thanks for your help 😄

**Comment by xenodium** [comment]
What version of Emacs are you running? `string-replace` should be part of Emacs in`subr.el.gz`. For me, it's under `/opt/homebrew/Cellar/emacs-plus@28/28.1/share/emacs/28.1/lisp/`.

**Comment by xenodium** [comment]
ps. Looks like `string-replace` was introduced in 28.1 https://www.gnu.org/software/emacs/news/NEWS.28.html

**Comment by strickinato** [comment]
Ah! Indeed, I'm on emacs 27.2.

I've been meaning to update, so this is probably the kick in the pants to do so. Thanks!!

(Perhaps change this line? https://github.com/xenodium/dwim-shell-command/blob/32a82c01359548527eb9a28c50963bc0dc662179/dwim-shell-command.el#L6)

**Comment by xenodium** [comment]
Lemme see if I can get it working on 27.1 instead. Can you try latest? Or pull changes in https://github.com/xenodium/dwim-shell-command/commit/af4d9778a2aef2423b63325502060653b19487fc and verify please?

**Comment by strickinato** [comment]
1. Confirmed it works in 28 🎉 

2. re: 27 - Looks like there's a similar problem with `file-name-concat` - which was also introduced in 28

**Comment by xenodium** [comment]
> 1. Confirmed it works in 28 🎉

Glad to hear.

> re: 27 - Looks like there's a similar problem with file-name-concat - which was also introduced in 28

Looks like you've managed to upgrade to 28. I've increased `Package-Requires` to 28.1, but please lemme know if you're staying on 27 and I'll make the effort to backport. Please reopen bug if so.

**Comment by strickinato** [comment]
Yup! managed to make it to 28 (also - because switching to native compilation, it took enough time, that in order to test 27, I took some time to figure out how to have both on my machine at the same time, which was an interesting learning experience.

Much appreciate your speedy response, and also all that you contribute to the emacs/macos world!!
