### ISSUE TITLE
fails with "Kill ring is empty" when the killring is empty :)

### ISSUE THREAD

**Issue by saucoide** [xenodium/dwim-shell-command#6]
When there is nothing on the killring, anything that calls to `dwim-shell-command--expand-file-template` fails with that error, even if `<<cb>>` is not being used

it comes from `(current-kill 0)` in:
```elisp
  (setq template (replace-regexp-in-string "\\(\<\<cb\>\>\\)" (or (current-kill 0)
                                                              (user-error "Nothing in clipboard"))
```

as long as you copy anything it works fine, but tripped me out when things stopped working on a recently restarted machine :)

I can reproduce it doing `(setq kill-ring nil)` and then running a dwim-shell-command

**Comment by xenodium** [comment]
Thanks for filing this bug @saucoide. Should be fixed now. Please reopen if otherwise. Ensure running 0.37 or newer.

**Comment by saucoide** [comment]
thanks, working now!
