### ISSUE TITLE
Embark integration

### ISSUE THREAD

**Issue by Gavinok** [xenodium/dwim-shell-command#7]
It would be nice to have a way to easily (or even automatically) integrate the existing commands with embark.

**Comment by xenodium** [comment]
Hiya Gavin. Thanks for filing. Could you describe the flow/integration a bit more? Not currently an embark user here.

Would a variable or a function returning a list of all available commands help here?

**Comment by Gavinok** [comment]
The idea was that you could call the built in dwim funcitons embark on say a file and it would execute on the file. This way you can use them outside of dired.

**Comment by xenodium** [comment]
> This way you can use them outside of dired

Would the current buffer's pointed file be enough? If so, that's currently supported. Say, you open any png image in image-mode, you can invoke `dwim-shell-commands-image-to-jpg` and it will execute on current file.

**Comment by Gavinok** [comment]
It was more so I could do it from find-file without having to actually open
the file

**Comment by xenodium** [comment]
I took a look at embark a little (I'm not a user), but it may be achieved with some embark configuration?

For example:

Modify `embark-file-map` to include `("&" dwim-shell-command)` and `embark-target-injection-hooks` to include something like `(dwim-shell-command embark--allow-edit)`

I'm sure there's a bit more needed. Maybe a custom version of the function `dwim-shell-command` maybe named `dwim-shell-command-embark-act` with a slightly different behavior.

Not too sure if that gets you in the right direction?

**Comment by bram85** [comment]
Instead, you could use `embark-export`, which will generate a Dired buffer when you're completing a file name. So you can use `dwim-shell-command` from there, no need to complicate things.

**Comment by xenodium** [comment]
Unfortunately I'm still not familiar with embark, but looks like dwim-shell-command is still compatible as is. Please correct me if otherwise. Will close issue. Thanks for the suggestion @bram85.
