### ISSUE TITLE
Add option to clean up the output buffers when the shell command succeeded

### ISSUE THREAD

**Issue by Dima-369** [xenodium/dwim-shell-command#8]
I would love to see an user option like `dwim-shell-command-delete-succeded-buffers` which deletes the buffers which can be nil by default. At the end of the day, I have many of those buffers open: `✅ *Clone dwim-shell-command* done` and I very rarely, if ever, need to check the buffer when the process succeeded - but entirely different story when it failed.

What do you think?

**Comment by xenodium** [comment]
There is a mechanism that does more or less what you're suggesting. For `dwim-shell-command-on-marked-files`, use `:silent-success t`. For `dwim-shell-command` prepend the command with a space.

ps. Also, `q` kills the `*Clone dwim-shell-command*` buffer.

**Comment by Dima-369** [comment]
> There is a mechanism that does more or less what you're suggesting. For dwim-shell-command-on-marked-files, use :silent-success t.

But that still keeps the buffer around and does not delete it.

For me, it's just a minor nitpick anyway. I added this into `(dwim-shell-command--finalize)` and all is well for me 😉 

```emacs-lisp
(with-current-buffer (process-buffer process)
  (kill-buffer))
```

**Comment by xenodium** [comment]
> But that still keeps the buffer around and does not delete it.

Oh. Maybe a bug? Just tried

`M-x dwim-shell-command` ` ls` (note the leading space).

And it remained silent and also killed the buffer on competion.

Looks like you're using one of the clone functions? Maybe `dwim-shell-commands-git-clone-clipboard-url`? Could you confirm?

**Comment by Dima-369** [comment]
I tried via this and the buffer stays around.

```emacs-lisp
(defun dima-dwim-shell-command-git-clone-clipboard-url ()
    "Clone git URL in clipboard to `default-directory'."
    (interactive)
    (dwim-shell-command-on-marked-files
     (format "Clone %s" (file-name-base (current-kill 0)))
     "git clone <<cb>>"
     :utils "git"
     :silent-success t
     :on-completion (lambda (_)
                      (shut-up
                        (dima-macos-notification "Cloned repository")))))
```

> M-x dwim-shell-command  ls (note the leading space).
>
> And it remained silent and also killed the buffer on competion.

Yup, I can confirm that this works as expected in this case.

**Comment by xenodium** [comment]
Ah, when using `:on-completion` one loses the default buffer killing logic. Take a look at `dwim-shell-commands-git-clone-clipboard-url-to-downloads`, which manually kills the buffer on completion.

Unrelated... I'm also a macOS user. What's in your `dima-macos-notification`? ;)

**Comment by xenodium** [comment]
Better to leave the snippet here... The following should work.

```
:on-completion (lambda (buffer)
                 (kill-buffer buffer)
                 (shut-up
                   (dima-macos-notification "Cloned repository")))
```

**Comment by Dima-369** [comment]
> What's in your dima-macos-notification? ;)

Oh, nothing fancy. I use `terminal-notifier` (installed by `brew`):

```emacs-lisp
(defun dima-macos-notification-message (title subtitle multi-line-message)
  "Log the parameters via `message'."
  (if multi-line-message
      (message (s-trim (format "%s\n\n%s" title subtitle)))
    (message "%s" (s-truncate
                   111
                   (s-replace "\n" "   " (s-join ": " (-non-nil (list title subtitle))))))))

(defun dima-macos-notification
    (title &optional subtitle multi-line-message)
  "Display an alert notification via terminal-notifier."
  (call-process-shell-command
   (format "terminal-notifier -title '%s' -subtitle '%s'&"
           title (or subtitle "Emacs"))
   nil 0)
  (dima-macos-notification-message title subtitle multi-line-message))
```
